# Generated by Django 5.0.6 on 2024-06-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinghour',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='workinghour',
            unique_together=set(),
        ),
    ]
