# Generated by Django 5.0.3 on 2024-06-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='license_number',
            field=models.CharField(max_length=50),
        ),
    ]
