# Generated by Django 5.0.6 on 2024-06-05 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_workinghour_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='exoerience',
            new_name='experience',
        ),
    ]
