# Generated by Django 5.0.4 on 2024-05-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('License', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Degree', models.CharField(max_length=200)),
                ('Experience', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=200)),
                ('Time_table', models.DateTimeField()),
            ],
        ),
    ]
