# Generated by Django 5.0.3 on 2024-06-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_clinic_license_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinghour',
            options={},
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='exoerience',
            new_name='experience',
        ),
        migrations.AlterUniqueTogether(
            name='workinghour',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='license_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
