# Generated by Django 5.0.6 on 2024-06-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_expertise_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='time',
            field=models.TimeField(),
        ),
    ]
