# Generated by Django 5.0.6 on 2024-06-06 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_rename_exoerience_doctor_experience'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('ClientID', 'time_start', 'SchedulingID', 'Status')},
        ),
    ]
