# Generated by Django 5.0.4 on 2024-05-01 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('Expertise_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Treating_Time', models.TimeField()),
                ('Expertise_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='Photo',
            field=models.ImageField(default='', upload_to='doctor_photos/'),
        ),
        migrations.CreateModel(
            name='Doc_Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_License', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_license_exp', to='myApp.doctor')),
                ('Expertise_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_exp_license', to='myApp.expertise')),
            ],
        ),
        migrations.CreateModel(
            name='Hiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_table', models.DateTimeField()),
                ('ClinicID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_hiring', to='myApp.clinic')),
                ('DoctorLicense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_hiring', to='myApp.doctor')),
            ],
        ),
    ]
