# Generated by Django 5.0.6 on 2024-06-05 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='time',
            field=models.TimeField(default=datetime.time(1, 0)),
        ),
    ]
