# Generated by Django 5.0.4 on 2024-05-01 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_expertise_doctor_photo_doc_expertise_hiring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('Client_email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Gender', models.CharField(max_length=5)),
                ('Phone', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Occupation', models.CharField(max_length=200)),
                ('Birth', models.DateField()),
                ('Checking_Notification', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField()),
                ('Status', models.IntegerField(choices=[(0, 'reserved'), (1, 'checkin failed'), (2, 'checkin successed'), (3, 'in treatment'), (3, 'finish')], default=0)),
                ('Client_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsv_client', to='myApp.client')),
                ('Clinic_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_clinic', to='myApp.clinic')),
                ('Doctor_License', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_doc', to='myApp.doctor')),
                ('Exp_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eservation_Exp', to='myApp.expertise')),
            ],
        ),
        migrations.CreateModel(
            name='Waiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField()),
                ('Status', models.BooleanField()),
                ('Client_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiting_client', to='myApp.client')),
                ('Clinic_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiting_reservation_clinic', to='myApp.clinic')),
                ('Doctor_License', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiting_reservation_doc', to='myApp.doctor')),
                ('Exp_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiting_reservation_Exp', to='myApp.expertise')),
            ],
        ),
    ]
