# Generated by Django 5.0.4 on 2024-05-01 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_client_reservation_waiting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
